## DSACADEMY
=================

## Pandas

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data. In pandas, a data table is called a DataFrame.


**Objectives**:
- Creating Dataframes (from excel or manually)
- Navigating a Dataframe 
- Modifying a Dataframe

In [3]:
# Let's import the pandas library

import pandas as pd

### What is a DataFrame?

Dataframes are just fancy excel tables in python. They can store many different types of data including characters, integers, floating point values, categorical data and more in columns

<p align="center" style="background-color: white; padding: 10px;">
    <img src="../images/01_table_dataframe.svg" alt="Dataframe" width="400" style="background-color: white;">
</p>


Each column in a DataFrame is a **Series**

<!-- Centering using an HTML paragraph tag -->
<p align="center">
  <img src="../images/week_2_1.png" alt="Alt text" width="400">
</p>

### How to create a DataFrame?

You can either:
- Create it with the `pd.DataFrame()` function

    ```sql
    df = pd.DataFrame(
        data={}
    )
    ```


- Import a tabular dataset like a spreadsheet (csv/excel) or a parquet using `pd.import_csv()`
    ```sql
    df = pd.import_csv(
        path=""
    )
    ```


Let's look at how to create it with the `pd.DataFrame()` function first

In [ ]:
# We will create a DataFrame of names and ages using a dictionary.
## NOTE: The keys of the dictionary will be the column names and the values will be the data for each column.

dictionary_data = {
    "name": ["Nathushan", "Jerry", "Sameer", "Adil"],
    "age": [18, 25, 35, 30]
}

print(dictionary_data)

{'name': ['Nathushan', 'Jerry', 'Sameer', 'Adil'], 'age': [18, 25, 35, 30]}

In [ ]:
# Now we pass the dict object as input to the data parameter of the DataFrame function and assign it to df variable.

df = pd.DataFrame(
    data=dictionary_data
)

df # NOTE: No need to use print() to display a dataframe in jupyter notebook.

        name  age
0  Nathushan   18
1      Jerry   25
2     Sameer   35
3       Adil   30

In [ ]:
# Awesome we just created our first DataFrame!
# It's still pretty small, so here's a bigger dataset

bigger_dataset = {
    "name": [
        "Nathushan", "Jerry", "Sameer", "Adil", "Kasun",
        "Dinesh", "Tharushi", "Nethmi", "Ahamed", "Sahan",
        "Dilshan", "Kavindi", "Ravindu", "Fathima", "Chamod"
    ],

    "age": [
        18, 25, 35, 30, 22,
        28, 21, 24, 32, 19,
        27, 23, 31, 26, 20
    ],

    "gender": [
        "Male", "Male", "Male", "Male", "Male",
        "Male", "Female", "Female", "Male", "Male",
        "Male", "Female", "Male", "Female", "Male"
    ],

    "job": [
        "Student", "Software Engineer", "Teacher", "Business Owner",
        "Student", "Accountant", "Nurse", "Graphic Designer",
        "Bank Manager", "Farmer", "Web Developer", "Teacher",
        "Electrician", "Government Officer", "Sales Executive"
    ],

    "salary_lkr": [
        25000, 180000, 95000, 150000, 30000,
        120000, 85000, 110000, 200000, 60000,
        175000, 90000, 80000, 130000, 100000
    ],

    "phone": [
        "0712345678", "0773456789", "0754567890", "0765678901",
        "0716789012", "0787890123", "0728901234", "0779012345",
        "0751122334", "0762233445", "0713344556", "0784455667",
        "0725566778", "0776677889", "0757788990"
    ],

    "vehicle": [
        None, "Toyota Aqua", "Honda Vezel", "Toyota Prius",
        None, "Suzuki Alto", None, None, "Toyota Aqua",
        None, "Honda Civic", "Toyota Aqua",
        "Yamaha FZ", "Toyota Axio", None
    ],

    "marital_status": [
        "Single", "Single", "Married", "Married", "Single",
        "Married", "Single", "Single", "Married", "Single",
        "Single", "Single", "Married", "Single", "Single"
    ]
}

In [ ]:
# Fit the dictionary data into a DataFrame and assign it to df variable.

df = pd.DataFrame(
    data=bigger_dataset
)

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,NaN,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,35,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single

### Viewing DataFrame

This dataset is bigger than the last so lets take a look at the top 5 rows only.

In [14]:
df.head()

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,NaN,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,35,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single

To see the bottom 5 you can use `df.tail()`

In [20]:
df.tail()

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Yamaha FZ,Married
13,Fathima,26,Female,Government Officer,130000,0776677889,Toyota Axio,Single
14,Chamod,20,Male,Sales Executive,100000,0757788990,NaN,Single

You can view a statistical summary of the **numerical** columns dataset with the `.describe()` function

In [ ]:
# This tells us the average age is 26.4 years, the average salary is 108,866 LKR.

df.describe()

             age     salary_lkr
count  15.000000      15.000000
mean   25.400000  108666.666667
std     5.082182   51874.390415
min    18.000000   25000.000000
25%    21.500000   82500.000000
50%    25.000000  100000.000000
75%    29.000000  140000.000000
max    35.000000  200000.000000

In [22]:
# Another really important function is info(). This tells the column datatypes and missing values.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            15 non-null     str
 1   age             15 non-null     int64
 2   gender          15 non-null     str
 3   job             15 non-null     str
 4   salary_lkr      15 non-null     int64
 5   phone           15 non-null     str
 6   vehicle         8 non-null      str
 7   marital_status  15 non-null     str
dtypes: int64(2), str(6)
memory usage: 1.1 KB

### Selecting DataFrame

Let's look at the following functions that will help us navigate the dataframe

- If you know the column names use:
    ```sql
    df['col_a'] 
    ```
    
- If you need to get specific rows of that column use:

    ```sql 
    df.loc[[0:10], [col_a]]
    ```

In [ ]:
# Let's select just the age column.

df["age"]

0     18
1     25
2     35
3     30
4     22
5     28
6     21
7     24
8     32
9     19
10    27
11    23
12    31
13    26
14    20
Name: age, dtype: int64

In [23]:
# We can also select multiple columns by passing a list of column names to the DataFrame.

df[["name", "age", "job"]]

         name  age                 job
0   Nathushan   18             Student
1       Jerry   25   Software Engineer
2      Sameer   35             Teacher
3        Adil   30      Business Owner
4       Kasun   22             Student
5      Dinesh   28          Accountant
6    Tharushi   21               Nurse
7      Nethmi   24    Graphic Designer
8      Ahamed   32        Bank Manager
9       Sahan   19              Farmer
10    Dilshan   27       Web Developer
11    Kavindi   23             Teacher
12    Ravindu   31         Electrician
13    Fathima   26  Government Officer
14     Chamod   20     Sales Executive

In [ ]:
# Let's say i want to get rows 10 to 13 of the DataFrame only.
# This is called slicing. We can slice a DataFrame by passing the start and end index to the DataFrame.

df[10:13]

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Yamaha FZ,Married

In [29]:
# If you want to save this slice to a new variable, you can do so like this:

df_slice = df[10:13]

In [30]:
df_slice

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Yamaha FZ,Married

Let's get only Sameer's age. 

We can do this using the `.loc[]` function

The `.loc[arg_1, arg_2]` function takes in 2 arguments.

1. The row index label (Example: Our index label is labelled 0,1,2,3,4...) 
2. The column label (Example: "gender")

In [38]:
df.head()

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,NaN,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,35,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single

In [39]:
# We can tell Sameer's row index is 2. So we can use the .loc() function to get his age.

print(df.loc[2,"age"])

35

Sameer tells us that his age is not 35 but its 38. Let's update his age in the DataFrame.

In [41]:
# We can also overwrite it

df.loc[2,"age"] = 38

In [46]:
df.head()

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,NaN,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,38,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single

Now lets get all the names that are single

We can use conditionals for DataFrames which look like:

```python
df[df[age] > 10]
```

In [ ]:
df[df['marital_status'] == 'Single']

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,NaN,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single
6,Tharushi,21,Female,Nurse,85000,0728901234,NaN,Single
7,Nethmi,24,Female,Graphic Designer,110000,0779012345,NaN,Single
9,Sahan,19,Male,Farmer,60000,0762233445,NaN,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single
13,Fathima,26,Female,Government Officer,130000,0776677889,Toyota Axio,Single
14,Chamod,20,Male,Sales Executive,100000,0757788990,NaN,Single

How about we get only singles over 20?

Here we will need 2 conditions instead of 1.

In [ ]:
df[(df['marital_status'] == 'Single') & (df['age'] > 20)]

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
4,Kasun,22,Male,Student,30000,0716789012,NaN,Single
6,Tharushi,21,Female,Nurse,85000,0728901234,NaN,Single
7,Nethmi,24,Female,Graphic Designer,110000,0779012345,NaN,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single
13,Fathima,26,Female,Government Officer,130000,0776677889,Toyota Axio,Single

Okay enough of adding conditionals there. Say i want to see everyone thats a:
- Nurse
- Teacher
- Web Developer

In [60]:
# While we can do it like

df[(df['job'] == 'Nurse') | (df['job'] == 'Teacher') | (df['job'] == 'Web Developer')]

# It's too long and not scalable.

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
2,Sameer,38,Male,Teacher,95000,0754567890,Honda Vezel,Married
6,Tharushi,21,Female,Nurse,85000,0728901234,NaN,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single

In [ ]:
# Instead try using the .isin([]) function. Pass a list of elements to check.

df[df['job'].isin(['Teacher', 'Web Developer', 'Nurse'])]

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
2,Sameer,38,Male,Teacher,95000,0754567890,Honda Vezel,Married
6,Tharushi,21,Female,Nurse,85000,0728901234,NaN,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,NaN,Single

### Missing Values

Almost always you will have missing data in the industry. 

Let's look into how to identify and manage them.

- To **identify** we can reuse the `df.info()` function
- To **drop** those values can use the `df.dropna()`
- To **fill** those values we can use `df.fillna()`

In [65]:
# Like before we can use the .info() function to help with finding null or missing values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            15 non-null     str
 1   age             15 non-null     int64
 2   gender          15 non-null     str
 3   job             15 non-null     str
 4   salary_lkr      15 non-null     int64
 5   phone           15 non-null     str
 6   vehicle         8 non-null      str
 7   marital_status  15 non-null     str
dtypes: int64(2), str(6)
memory usage: 1.1 KB

In [67]:
# From the above info we can see that vehicle column has only 8 non-null values 
# which means the rest is null 

# NOTE: NaN is the missing/empty values here

df['vehicle']

0                NaN
1        Toyota Aqua
2        Honda Vezel
3       Toyota Prius
4                NaN
5        Suzuki Alto
6                NaN
7                NaN
8     Toyota Corolla
9                NaN
10       Honda Civic
11               NaN
12         Yamaha FZ
13       Toyota Axio
14               NaN
Name: vehicle, dtype: str

Now we can either drop the rows or the column of the null values.

Here is what it looks like with NaN rows dropped.

In [69]:
df.dropna(
    axis=0  # 0 is row and 0 is column
)

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,38,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
5,Dinesh,28,Male,Accountant,120000,0787890123,Suzuki Alto,Married
8,Ahamed,32,Male,Bank Manager,200000,0751122334,Toyota Corolla,Married
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Yamaha FZ,Married
13,Fathima,26,Female,Government Officer,130000,0776677889,Toyota Axio,Single

Here is what it looks like with the NaN column ('Vehicle') dropped

In [70]:
df.dropna(
    axis=1
)

,name,age,gender,job,salary_lkr,phone,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Single
2,Sameer,38,Male,Teacher,95000,0754567890,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Married
4,Kasun,22,Male,Student,30000,0716789012,Single
5,Dinesh,28,Male,Accountant,120000,0787890123,Married
6,Tharushi,21,Female,Nurse,85000,0728901234,Single
7,Nethmi,24,Female,Graphic Designer,110000,0779012345,Single
8,Ahamed,32,Male,Bank Manager,200000,0751122334,Married
9,Sahan,19,Male,Farmer,60000,0762233445,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Married
13,Fathima,26,Female,Government Officer,130000,0776677889,Single
14,Chamod,20,Male,Sales Executive,100000,0757788990,Single

Now instead of dropping we can also fill the missing (NaN) values using `.fillna()`

In [ ]:
# First let's check how many times the vehicles have been mentioned using the value_counts() function.

df['vehicle'].value_counts()

vehicle
Toyota Aqua       1
Honda Vezel       1
Toyota Prius      1
Suzuki Alto       1
Toyota Corolla    1
Honda Civic       1
Yamaha FZ         1
Toyota Axio       1
Name: count, dtype: int64

In [ ]:
# Then we get the mode() of the column which is ranked by most common to least

df['vehicle'].mode()

0       Honda Civic
1       Honda Vezel
2       Suzuki Alto
3       Toyota Aqua
4       Toyota Axio
5    Toyota Corolla
6      Toyota Prius
7         Yamaha FZ
Name: vehicle, dtype: str

In [ ]:
# Then we use the most common vehicle to replace the NaN values.

df.fillna(
    value= df['vehicle'].mode()[0] # we need to pass a value to replace the NaN with.
)

,name,age,gender,job,salary_lkr,phone,vehicle,marital_status
0,Nathushan,18,Male,Student,25000,0712345678,Honda Civic,Single
1,Jerry,25,Male,Software Engineer,180000,0773456789,Toyota Aqua,Single
2,Sameer,38,Male,Teacher,95000,0754567890,Honda Vezel,Married
3,Adil,30,Male,Business Owner,150000,0765678901,Toyota Prius,Married
4,Kasun,22,Male,Student,30000,0716789012,Honda Civic,Single
5,Dinesh,28,Male,Accountant,120000,0787890123,Suzuki Alto,Married
6,Tharushi,21,Female,Nurse,85000,0728901234,Honda Civic,Single
7,Nethmi,24,Female,Graphic Designer,110000,0779012345,Honda Civic,Single
8,Ahamed,32,Male,Bank Manager,200000,0751122334,Toyota Corolla,Married
9,Sahan,19,Male,Farmer,60000,0762233445,Honda Civic,Single
10,Dilshan,27,Male,Web Developer,175000,0713344556,Honda Civic,Single
11,Kavindi,23,Female,Teacher,90000,0784455667,Honda Civic,Single
12,Ravindu,31,Male,Electrician,80000,0725566778,Yamaha FZ,Married
13,Fathima,26,Female,Government Officer,130000,0776677889,Toyota Axio,Single
14,Chamod,20,Male,Sales Executive,100000,0757788990,Honda Civic,Single

### Merging

There